### ISSUE TITLE
onError option does not work

### ISSUE THREAD

**Issue by alisnic** [logdna/pino-logdna#9]
When adding `onError` option to transporter, I get the following error:

```
DOMException [DataCloneError]: event => {
  // eslint-disable-next-line no-console
  console.error('LogDNA Error', event);
} could not be cloned.
    at new Worker (internal/worker.js:239:17)
    at createWorker (/Users/andreilisnic/Work/planable-app/node_modules/thread-stream/index.js:50:18)
    at new ThreadStream (/Users/andreilisnic/Work/planable-app/node_modules/thread-stream/index.js:209:19)
    at buildStream (/Users/andreilisnic/Work/planable-app/node_modules/pino/lib/transport.js:40:18)
    at transport (/Users/andreilisnic/Work/planable-app/node_modules/pino/lib/transport.js:124:10)
    at normalizeArgs (/Users/andreilisnic/Work/planable-app/node_modules/pino/lib/tools.js:419:16)
    at pino (/Users/andreilisnic/Work/planable-app/node_modules/pino/pino.js:86:28)
```

I'm initializing the logger like this:
```js
{
  target: 'pino-logdna',
  level,
  options: {
    key: logdnaKey,
    app: Meteor.settings.public.appName,
    env: process.env.NODE_ENV,
    indexMeta: true,
    onError: onLogDNAError,
    hostname
  }
}

```
If a test is adjusted to pass this option, the test suite freezes:

```diff
diff --git a/test/stream.js b/test/stream.js
index c7e9c11..98d6b98 100644
--- a/test/stream.js
+++ b/test/stream.js
@@ -70,6 +70,7 @@ test('pinoLogdna', async (t) => {
     , tags: 'foo,bar'
     , indexMeta: true
     , messageKey: 'message'
+    , onError: (event)=> { console.log(event) }
     }
```

**Comment by mdeltito** [comment]
@alisnic thanks for reporting this, it looks like this was missed when upgrading the transport to support Pino 7.x. The error is due to the options for the transport being serialized when passed into the `worker_thread`.

The `onError` option should no longer be necessary - you can instead attach the error handler directly after initializing the transport:

```js
transport.on('error', (err) => {
  console.log(err)
})
```

**Comment by alisnic** [comment]
Thanks for prompt response @mdeltito!

**Comment by alisnic** [comment]
One quick question, will this help in case my app crashes? I get this on production once in a while:

```
Error: A connection-based error occurred that will not be retried. See meta data for details.nd3rg
  at /app/bundle/programs/server/npm/node_modules/@logdna/logger/lib/logger.js:859:25nd3rg
  at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

And trying to mitigate this by registering an error handler and logging the error. Crashing the app is not the best course of action in case there is a connection error

**Comment by mdeltito** [comment]
@alisnic yes, attaching an error handler will solve this - the following should actually work for you instead of my previous comment.

Since the `onError` callback function in the options cannot be serialized across worker threads, you can instead implement a wrapper around the configuration in a separate file:

```js
// your main code where `pino` is configured
const pino = require('pino')

...

const transport = pino.transport({
  // note the `target` points at a file instead of `pino-logdna`
  target: './logdna-transport.js'
, options: {
    key: logdnaKey
  , app: Meteor.settings.public.appName
  , env: process.env.NODE_ENV
  , indexMeta: true
  , hostname
  }
}

const log = pino({}, transport)
// use `log` as you normally would
```

Then the `logdna-transport.js` wrapper:

```js
const logdna = require('pino-logdna')

module.exports = function createLogdnaTransport(opts) {
  return logdna({
    ...opts
  , onError: (err) => {
      // handle errors here
      console.log(err)
    }
  })
}
```

**Comment by mdeltito** [comment]
@alisnic just following up here, if you don't mind reporting back if this worked for you I will get this added to the docs. Thanks again!

**Comment by alisnic** [comment]
Yes it worked, thank you!
